name: NeroDungeons
main: com.nerokraft.nerodungeons.NeroDungeons
version: 1.0
api-version: 1.15
commands:
  nd:
    description: Manage NeroDungeons
    permission: nerodungeons.nd
    usage: nd [createdungeon,createshop]
permissions:
  nerodungeons.nd:
    description: give access to /nd command
    default: false
  nerodungeons.createshop:
    description: allow user to create shops
    default: false