name: NeroDungeons
main: com.nerokraft.nerodungeons.NeroDungeons
version: 1.0
api-version: 1.15
commands:
  nerodungeon:
    description: base nerodungeons command
    aliases: nd
permissions:
  nerodungeons.admin:
    description: All permissions
    default: op
  nerodungeons.verbose:
    description: Turn on verbose output
    default: op