name: NeroDungeons
main: com.nerokraft.NeroKraft
version: 0.1
api-version: 1.15
commands:
  nerodungeon:
    description: base nerodungeons command [nd cs|rs]
    aliases: nd
permissions:
  nerodungeons.admin:
    description: All permissions
    default: op
  nerodungeons.verbose:
    description: Turn on verbose output
    default: op
  nerodungeons.createshop:
    description: Allowed to make shops
    default: op
  nerodungeons.sell:
    description: Sell a product to a shop that will buy them
    default: true
  nerodungeons.buy:
    description: Buy any products
    default: true
  nerodungeons.buy.many:
    description: Buy & sell more than one set at a time
    default: true
  nerodungeons.buy.own:
    description: Buy & sell own products
    default: op
  nerodungeons.nocapital:
    description: Buy without money
    default: op